### ISSUE TITLE
[BUG] Every request for an unsupported language triggers requests to Singleton service.

### ISSUE THREAD

**Issue by jessiejuachon** [vmware/singleton#1456]
**Describe the bug**
For every request for a unsupported language received by the client application, the Ruby client library sends a requests to Singleton service.

**To Reproduce**
1. Run any Ruby application that uses the Singleton Ruby client library.
2. Send a request to the client application for translations in an unsupported language.
3. Notice that for every request in step 2, the client application sends a request to Singleton service to fetch the non-existent translations.

**Expected behavior**
1. At startup, the client application should fetch the list of supported languages from Singleton service, and add the list to client-side cache.
2. When a request for translations in an unsupported language is sent to the client application, the Singleton Ruby client library should check the list of supported languages in cache, find that the requested language is not supported, and serve the source language.
3. Simultaneously, the Singleton ruby client library should also check if the cached list of supported languages has expired. If yes, the cache should be refreshed in parallel.

Note: The above behavior is expected for both single-string (getString) and component-strings (getStrings) queries.
References: 
https://confluence.eng.vmware.com/x/fuGgHw
https://confluence.eng.vmware.com/x/x2RQMQ

**Comment by InaSong** [comment]
This is focusing on Singleton API improvement.

**Comment by lyiyu66** [comment]
This issue is separated as below two:
1)Fix non-supported languages the request is per page loading, with this fix the getString/getStrings APIs will request one time, if get empty response it will use local source bundle afterwards until 1hr later to try remote again.
--That is what fix in #1461.
2)Supported locale list fetch, then use locale list cache to prejudge the requested locale whether is supported, yes→go to service fetch, no→return source directly without http connect. It has been tracked with issue #1473.

**Comment by lyiyu66** [comment]
The item #1 in [above comment](https://github.com/vmware/singleton/issues/1456#issuecomment-1038165563) has been fixed. Hence closing this issue.
