### ISSUE TITLE
 [BUG] [Ruby Client] (getStrings API)When requesting translation, client should return source if source has been changed. 

### ISSUE THREAD

**Issue by linr211** [vmware/singleton#1558]
For getStrings API, when requesting translation, client should return source if source has been changed.

**Comment by lyiyu66** [comment]
Checked with build 0.7.0.36 with commit 09f7be8d62b86f6ae5c891a3c7d7e175059fa313, the issue is fixed.
Case1:
When some of keys in a component has been updated, requesting non-EN supported locale(example: ja), getStrings and get_translations() api return:
ja translation(for the source is same as messages_en.json) + source(en) string(for the source is not same as messages_en.json)
Case2:
New key/value pairs are added to source file, requesting non-EN supported locale(example: ja), getStrings and get_translations() api return:
ja translation(for the source is same as messages_en.json) + source(en) string(for the source is not same as messages_en.json if has) + new added source(en) string
