### ISSUE TITLE
[BUG] [Ruby Client](translate) When input argument in less than require argument, it should throw error rather than return key

### ISSUE THREAD

**Issue by dleng-vmware** [vmware/singleton#1693]
**Describe the bug**
(translate) When input argument in less than require argument, it should throw error rather than return key

**To Reproduce**
1. the translate require number of arguments are 2 or 3
2. Singleton.translate('about.message' , name:"xsdsad")
Client return 'about.message'

**Expected behavior**
Client should throw error ArgumentError: wrong number of arguments (given 1, expected 2..3)

**Comment by Xiaochao8** [comment]
Ruby treats `name:"xsdsad"` as the second argument,so no errors are thrown. Then `name:"xsdsad"` becomes the component name. This is fine because client will verify if a bundle (component/locale) is valid, and client will return key if it isn't valid.

After disscussion with our QEs, we agree to close this.
