### ISSUE TITLE
[BUG][Go service][JS client]Failed to download pattern data from go service with cli and pattern data can't be gotten in offline mode.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#2035]
**Describe the bug**
Go service: 76e82d48e8cf290623b6073fffddb31b1d9d7def
JS client: 9f304f87c0b182a750008b91e914af34a92d5c8d
Failed to download pattern data from go service with cli. And pattern data can't be gotten in offline mode.

**To Reproduce**
1. Start go service.
2. Set the script in package.json file of JS client:
```
"scripts": {
...
    "load-locale-data": "load-locale-data --directory ./resources/assets/i18n --product JSCoreSDKTest --component sunglow --host http://localhost:8091 --version 1.0.0 --locales fr-ch,zh-Hans --scope dates,numbers,currencies"
...
  }
```
3. Run the command: npm run load-locale-data
4. See error:
![image](https://user-images.githubusercontent.com/51813046/210687745-c6335290-deca-483f-b93d-3c2ed79b8f15.png)

**Expected behavior**
Translation and pattern can be downloaded and stored successfully.

**Comment by Xiaochao8** [comment]
The expected type of `pseudo` field is `string` which is same in Java service, but client sends it as type `bool` which is wrong. Here are the suggestions.

- Client can use the `GET` interface because `POST` interface has been deprecated.

OR

- Client removes `pseudo` from request arguments because `pseudo` is `false` by default.

@sjiang-cb Please check.

**Comment by Xiaochao8** [comment]
Go service combine POST interface can accept both string type and boolean type as pseudo field.
