### ISSUE TITLE
[Java Client] Support to get multiple-version translation

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#2665]
To meet the requirement,  some updates that needed in Java Client:
1. In the config file, the "version" can be multiple values seperated by comma or 'all'.
 ```
# It's used for categorizing translation by product on Singleton side to maintain translation.
productName = JavaclientTest
 
# Define the translation's version used by Singleton service. Only one of below 2 items need to be defined, if your product only have one version, define 'version' is enough; if you have multiple versions, define 'versions'.
#version = 1.0.0
versions = 1.0.0,2.0.0,3.0.0/all
...
```
2. Add a new API with a 'version' parameter, which specify which version's translation is needed. At the bottom layer of this API, it call Singleton service API for online mode to get multiple versions' translation of one key.
```
public String getMessage(final String version, final Locale locale, final String component, final String key, final Object... args) {
     ...
}
```

**Comment by huihuiw01** [comment]
Since the PR https://github.com/vmware/singleton/pull/2783 mainly fix the review comments of the implementation of multi-version API(PR https://github.com/vmware/singleton/pull/2698), no logic change, so only need run the regression tests for this API.

But another logic change is when locale is null, set it to default locale instead of throw exception as bug https://github.com/vmware/singleton/issues/1515 expected.

**Comment by lyiyu66** [comment]
The regression testing on 'getMessage', 'getMessages' and 'getMultiVersionMessage' APIs are PASS with commit f1f6a909a7452d8652148ce242a51b86cde0d25f
