### ISSUE TITLE
[BUG] [Java Client]When getMessages() returns to default locale's translation, cache can't get updated translation(default locale) after it is expired.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#664]
**Describe the bug**
Online or Mixed mode: When getMessages() returns to service default locale's translation, cache can't get updated translation(default locale) after it is expired.

**To Reproduce**
1. Set config with pure online or mixed mode.
2. Request a locale doesn't have its translation in service with getMessages(locale, component), then it will return default locale's translation from service.
3. Get one key's value from step2 returned result.
4. Update the default locale's value of that key and set the cache expired.
5. Repeat the request in step 2.
6. Repeat the request in step 2.
7. Repeat step 3.
Still get the original translation of default locale rather than the updated translation in step 4.

**Expected behavior**
Should get the updated translation of default locale once cache is expired and request is sent.

**Comment by lyiyu66** [comment]
The issue also is reproducible when getMessages() return to default locale's translation from offlineBundles.

**Comment by jessiejuachon** [comment]
(Pasting the same comment I put in issue #662 )

I just tested this and it works for me. I am guessing there is something wrong with the steps you wrote above. Please check the following:

In step 2, how is the client cache expire time set? If you are testing the new client workflow, make sure to NOT set the cacheExpiredTime property in the properties config file. Otherwise, cacheExpiredTime will be used instead of the value set by the Singleton service in the cache-control max age header in the HTTP response.
In step 3, which default locale message do you update? Since you are testing online or mixed mode, you should update the message in the service because that takes priority over the offline message.
In step 3, how do you expire the client-side cache?
If the client had previously cached the response and its expire time (either using the cacheExpiredTime config or the cache-control max age header), then the cached messages will only expire after the configured expire time. Do you wait for the time to pass, or do you have some other way to expire the time?

**Comment by lyiyu66** [comment]
- I have set the cache expired time as 0l in config file to make cacheExpiredTime use new workflow(from http response header).
vipCfg.setCacheExpiredTime(0l);

- Depends on which default locale message is used. If it uses service default locale message(when service has requested component with default locale), then update the service side's, else(when service hasn't the requested component with default locale, but offlineBundles has), update offline message.

- Yes, I set cacahItem.setMaxAgeMillis(0l) or 1000l, then thread.sleep(2000), and also use cacheItem.isExpired() to check the expired status.

**Comment by jessiejuachon** [comment]
@lyiyu66  , this is ready for testing. One detail to change un your script: Call tm.getMessage(,..) before tm.getMessage(,..). Only the call to the expired locale is able to update the expired locale's cache.
The requested locale can just read the default locale's cache in case of failure, but not trigger any update for the default locale.

**Comment by jessiejuachon** [comment]
@lyiyu66 , this is now ready for testing

**Comment by surite** [comment]
Test pass on commit 3b6f338c9c06dd6457baf6271eb2c21f7fed8aeb.
