### ISSUE TITLE
[BUG] [Java Client]Pattern(Date time/Number/Currency/Percent) fail to fallback to source locale if requested and default locale can't be fetched successfully.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#758]
**Describe the bug**
Pattern(Date time/Number/Currency/Percent) fail to fallback to source locale if requested and default locale can't be fetched successfully.

**To Reproduce**
1. Set defaultlocale = invaild and sourcelocale = de in java config properties file.
2. Request a invalid locale(e.g. abc) to get patterns((Date time/Number/Currency/Percent).

**Expected behavior**
Should get de locale's patterns.

**Screenshots**
Example of get number pattern
![image](https://user-images.githubusercontent.com/51813046/92328520-fe911080-f093-11ea-887b-246a74c90159.png)

**Comment by huihuiw01** [comment]
The reason for this issue is Jessiely required L2 use the same fallback locales chain as L3, and in the chain source locale is hardcode as 'source', doesn't use the source locale configed in the config file. 
But there are resource files suffixed with 'source' for L3, no such files for L2, so this bug occurred.

Need discuss if this fallback chain is appropriate to L2.

**Comment by huihuiw01** [comment]
@jessiejuachon After discussion with Demin and team members in last Friday's sprint review meeting, the conclusion of the fallback queue for L2 is:

requested locale -> default locale -> English locale

As L2 has nothing to do with source locale.

**Comment by jessiejuachon** [comment]
Proposed solution: Use LocaleUtility.getSourceLocale in L2 workflow whenever locale = "source" in locale fallback queue
Also, can we change priority to low?

**Comment by lyiyu66** [comment]
Lower the priority to low as the corresponding data about default locale is always available.

**Comment by jessiejuachon** [comment]
Discussed with Huihui and Xiaochao, then with Demin. Here's the conclusion:
Use the same locale fallback queue for L2 and L3. 

Using the source locale must not happen in production because default locale should be always available. If source locale is used instead of default, then it is a pre-deployment bug that g11n QE must report. 

Having said that, the bug that Yiyu filed is valid, but of low priority. This is because it is expected to always find the default locale for L2 in production so it shouldn't even reach source locale. Nonetheless, to solve the bug, we should use getSourceLocale for L2. 

Here is my proposed code changes to Huihui's PR: https://github.com/huihuiw01/singleton/pull/1/files

**Comment by huihuiw01** [comment]
After discussion on Jan 22 2021, the final conclusion for L2 fallback is: 
requested locale -> default locale

And L2 data for default locale should be always available, so no chance to fallback to source locale, so the case mentioned in this bug is not valid.

If fallback to default locale fails, bug should be reported by QE.

**Comment by lyiyu66** [comment]
According to dev's comment, default locale pattern always is here. So no need to fallback to source locale pattern.
