### ISSUE TITLE
[Java Client][Documentation] Update Java client API document for 0.5.1 release

### ISSUE THREAD

**Issue by gong-yu** [vmware/singleton#840]

**Comment by jessiejuachon** [comment]
Reference: https://confluence.eng.vmware.com/display/~jjuachon/New+Features+in+the+VIP+Java+Client+Library

**Comment by jessiejuachon** [comment]
@gong-yu , where should the official release document be located?

**Comment by jessiejuachon** [comment]
Hi @gong-yu . Could you remind me which document this issue is referring to? I am planning to pull this into sprint 96.

I see this: https://vmware.github.io/singleton/docs/overview/singleton-sdk/java-client-introduction/ but do not know how to update the text in it.

I see the this: https://github.com/vmware/singleton/blob/website/content/en/docs/tutorials/integrate-singleton-in-java-app.md, but it seems it only has a reference to the first link above, and also to the sample app, so I do not see much to update.

**Comment by jessiejuachon** [comment]
Updates can be seen here: https://vmware.github.io/singleton/docs/overview/singleton-sdk/java-client-introduction/

Javadoc is displayed here: https://vmware.github.io/singleton/docs/overview/singleton-sdk/resources/javadoc/
Javadoc is stored here: https://github.com/jessiejuachon/singleton/tree/website/content/en/docs/overview/singleton-sdk/resources/javadoc

**Comment by nannany00** [comment]
@jessiejuachon , what's update for https://vmware.github.io/singleton/docs/overview/singleton-sdk/java-client-introduction/, I don't see any changes for this page, could you help to check anything missing? Thanks.
